server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: scaffold
  profiles:
    active: dev

  # Jackson 配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scaffold.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper 配置
pagehelper:
  # 设置数据库方言为 MySQL
  helper-dialect: mysql
  # 启用合理化分页参数处理（如 pageNum <= 0 时会显示第一页）
  reasonable: true
  # 支持通过 Mapper 接口方法的参数来传递分页参数
  support-methods-arguments: true
  # 指定 count 查询的方法名为 countSql
  params: count=countSql


# JWT 配置
jwt:
  secret: Hope-I-am-Always-Happy-And-My-Family-is-Healthy
  # 1小时（毫秒）
  expiration:  3600000
  header: Authorization
  prefix: Bearer

# 日志配置
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    com.scaffold: debug
    com.scaffold.mapper: debug